[package]
name = "wabot"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.serenity]
verion = "0.10"
git = "https://github.com/serenity-rs/serenity.git"
features = [
    "builder",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
